In [1]:
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt
from IPython.display import HTML # It allows you to display raw HTML content directly in Jupyter Notebooks or IPython environments.

In [2]:
import zipfile
import os

# Define the ZIP file name (ensure it exists in the same directory or provide the full path)
zip_file_name = "PlantVillage.zip"

# Verify the ZIP file exists
if not os.path.exists(zip_file_name):
    raise FileNotFoundError(f"The file '{zip_file_name}' does not exist.")

# Create a directory to extract files
extract_path = "PlantVillage"
os.makedirs(extract_path, exist_ok=True)

# Extract ZIP file
try:
    with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    print(f"Files extracted to {extract_path}")
except zipfile.BadZipFile:
    print(f"The file '{zip_file_name}' is not a valid ZIP file.")


Files extracted to PlantVillage


In [3]:
!pip install split-folders

In [4]:
import splitfolders

# Split the dataset with the specified ratio
splitfolders.ratio('./PlantVillage', output='dataset', ratio=(0.7, 0.1, 0.2)) # Split into 70% training, 10% Validation , 20% Test and store in dataset name directory


Copying files: 2152 files [00:00, 4174.10 files/s]


In [5]:
IMAGE_SIZE = 256
CHANNELS = 3

In [8]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator( # This do data augmentation
        rescale=1./255,
        rotation_range=10,
        horizontal_flip=True
)
train_generator = train_datagen.flow_from_directory( # This do preprocessing of training data
        'dataset/train',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        batch_size=32,
        class_mode="sparse", # For simple integer labels
        # save_to_dir="Augmented_Extracted" # Save all Augmented images in it we not do in google colab
)

Found 1506 images belonging to 3 classes.


In [9]:
train_generator.class_indices

{'Potato___Early_blight': 0, 'Potato___Late_blight': 1, 'Potato___healthy': 2}

In [10]:
class_names = list(train_generator.class_indices.keys())
class_names

['Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy']

In [11]:
count=0
for image_batch, label_batch in train_generator:
#     print(label_batch)
    print(image_batch[0])
    break
#     count+=1
#     if count>2:
#         break

[[[0.6039627  0.55298233 0.58827645]
  [0.6039159  0.55293554 0.58822966]
  [0.6049896  0.5540092  0.5893033 ]
  ...
  [0.6533166  0.6062578  0.6454735 ]
  [0.64705884 0.6        0.6392157 ]
  [0.64705884 0.6        0.6392157 ]]

 [[0.5968711  0.5458907  0.5811848 ]
  [0.5962334  0.54525304 0.58054715]
  [0.5955126  0.54453224 0.57982635]
  ...
  [0.6551688  0.60810995 0.64732563]
  [0.649568   0.6025092  0.6417249 ]
  [0.6496638  0.602605   0.64182067]]

 [[0.6117228  0.56074244 0.59603655]
  [0.61073965 0.55975926 0.5950534 ]
  [0.60792613 0.55694574 0.59223986]
  ...
  [0.66362506 0.61656624 0.6557819 ]
  [0.6606757  0.6136169  0.65283257]
  [0.66210055 0.61504173 0.6542574 ]]

 ...

 [[0.49045917 0.42771408 0.43947878]
  [0.47779027 0.41504517 0.42680988]
  [0.4712323  0.4084872  0.4202519 ]
  ...
  [0.5069923  0.44424716 0.48346284]
  [0.48703703 0.42429194 0.46350762]
  [0.48085138 0.4181063  0.45732197]]

 [[0.51065713 0.44791204 0.45967674]
  [0.50672084 0.44397572 0.45574042]


In [12]:
validation_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=10,
        horizontal_flip=True)
validation_generator = validation_datagen.flow_from_directory(
        'dataset/val',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        batch_size=32,
        class_mode="sparse"
)

Found 215 images belonging to 3 classes.


In [13]:
test_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=10,
        horizontal_flip=True)

test_generator = test_datagen.flow_from_directory(
        'dataset/test',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        batch_size=32,
        class_mode="sparse"
)

Found 431 images belonging to 3 classes.


In [15]:
for image_batch, label_batch in test_generator:
    print(image_batch[0])
    break # if not apply break a generator print all images

[[[0.4760643  0.45645645 0.47998586]
  [0.49164206 0.47203422 0.49556363]
  [0.5132217  0.4936138  0.51714325]
  ...
  [0.74071276 0.7211049  0.7485559 ]
  [0.74055606 0.7209482  0.7483992 ]
  [0.7403993  0.7207914  0.74824244]]

 [[0.4757508  0.45614293 0.47967237]
  [0.48976108 0.47015324 0.49368265]
  [0.5165134  0.49690554 0.520435  ]
  ...
  [0.73587316 0.7162653  0.7437163 ]
  [0.7354029  0.71579504 0.743246  ]
  [0.73493266 0.7153248  0.7427758 ]]

 [[0.47543728 0.45582944 0.47935885]
  [0.4878801  0.46827227 0.49180168]
  [0.5198051  0.5001973  0.52372664]
  ...
  [0.7268626  0.70725477 0.73470575]
  [0.72733283 0.707725   0.73517597]
  [0.7278031  0.70819527 0.73564625]]

 ...

 [[0.52934504 0.5058156  0.51365876]
  [0.52856123 0.5050318  0.51287496]
  [0.52777755 0.50424814 0.5120913 ]
  ...
  [0.6320256  0.6084962  0.6163393 ]
  [0.64129496 0.6177655  0.6256087 ]
  [0.6673422  0.6438128  0.6516559 ]]

 [[0.5003104  0.476781   0.48462415]
  [0.49905643 0.47552702 0.48337016]


In [16]:
input_shape = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)
n_classes = 3

model = models.Sequential([
    layers.InputLayer(shape=input_shape),
    layers.Conv2D(32, kernel_size = (3,3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64,  kernel_size = (3,3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64,  kernel_size = (3,3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(n_classes, activation='softmax'),
])

In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 254, 254, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 127, 127, 32)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 125, 125, 64)        │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 62, 62, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 60, 60, 64)          │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (None, 30, 30, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (None, 28, 28, 64)          │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 14, 14, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_4 (Conv2D)                    │ (None, 12, 12, 64)          │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_4 (MaxPooling2D)       │ (None, 6, 6, 64)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_5 (Conv2D)                    │ (None, 4, 4, 64)            │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_5 (MaxPooling2D)       │ (None, 2, 2, 64)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 256)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 64)                  │          16,448 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 3)                   │             195 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 183,747 (717.76 KB)

 Trainable params: 183,747 (717.76 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=['accuracy']
)

In [19]:
history = model.fit(
    train_generator,
    steps_per_epoch=47,
    batch_size=32,
    validation_data=validation_generator,
    validation_steps=6, # After each validation it go to validate the model on 6 batches of val dataset
    epochs=20,
)

Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:122: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


47/47 ━━━━━━━━━━━━━━━━━━━━ 41s 578ms/step - accuracy: 0.4305 - loss: 0.9647 - val_accuracy: 0.4635 - val_loss: 0.8932
Epoch 2/20
 1/47 ━━━━━━━━━━━━━━━━━━━━ 3s 75ms/step - accuracy: 0.4688 - loss: 0.8862

/usr/lib/python3.11/contextlib.py:158: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(typ, value, traceback)


47/47 ━━━━━━━━━━━━━━━━━━━━ 7s 142ms/step - accuracy: 0.4688 - loss: 0.8862 - val_accuracy: 0.4783 - val_loss: 0.9379
Epoch 3/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 25s 470ms/step - accuracy: 0.5290 - loss: 0.8762 - val_accuracy: 0.5625 - val_loss: 0.9174
Epoch 4/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4375 - loss: 1.2035 - val_accuracy: 0.4783 - val_loss: 0.9288
Epoch 5/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 41s 462ms/step - accuracy: 0.6805 - loss: 0.7110 - val_accuracy: 0.7448 - val_loss: 0.5413
Epoch 6/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - accuracy: 0.8125 - loss: 0.4751 - val_accuracy: 0.7391 - val_loss: 0.4999
Epoch 7/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 37s 444ms/step - accuracy: 0.8165 - loss: 0.4582 - val_accuracy: 0.8385 - val_loss: 0.3586
Epoch 8/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8750 - loss: 0.3502 - val_accuracy: 0.7391 - val_loss: 0.6319
Epoch 9/20
47/47 ━━━━━━━━━━━━━━━━━━━━ 44s 534ms/step - accuracy: 0.8560 - loss: 0.3660 - val_accuracy: 0.8698 - val_l

In [20]:
scores = model.evaluate(test_generator)

14/14 ━━━━━━━━━━━━━━━━━━━━ 8s 536ms/step - accuracy: 0.9167 - loss: 0.1985


In [21]:
history

In [22]:
history.params

{'verbose': 1, 'epochs': 20, 'steps': 47}

In [23]:
history.history.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [24]:
type(history.history['loss'])

list

In [25]:
history.history['loss'][:5] # show loss for first 5 epochs

[0.9282885789871216,
 0.8862301111221313,
 0.8601488471031189,
 1.2034549713134766,
 0.6568520069122314]

In [26]:
# Assuming your model is stored in the variable `model`
model.save('my_model.h5')  # Saves the model to a file named 'my_model.h5'
